server:
  port: 8761

spring:
  application:
    name: eurekaserver

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eurekaserver
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
